Repository mcpyproject/McPy, pull requests merged in 2020-11, with the labels that each got.

#44 Move network logic into separate classes and files
  classes/__init__.py
  classes/network/Connection.py
  classes/network/PacketType.py
  classes/network/__init__.py
  classes/network/versions/__init__.py
  classes/network/versions/v578.py
  main.py
Labels: Enhancement, Need testing, Networking

#47 Remove prefixed tags
  docs/howto_git.md
Labels: Documentation

#40 Property based Unit testing
  test/utils/test_location.py
  test/utils/test_position.py
Labels: Need testing
