Repository mcpyproject/McPy, pull requests merged in 2021-01, with the labels that each got.

#53 Remove startup.py in favor of simpler dependencies.py
  README.md
  dependencies.py
  requirements.txt
  startup.py
Labels: Enhancement

#58 Consistent logging and allow users to set the logging format
  classes/mcPy/McPy.py
  classes/mcPy/Parser.py
  dependencies.py
Labels: Bugfix

#59 Fix server status issues
  classes/network/Connection.py
Labels: Bugfix

#60 Fix server list ping from future versions
  classes/network/Connection.py
Labels: Bugfix, Networking
