Repository mcpyproject/McPy, pull requests merged in 2021-03, with the labels that each got.

#66 Remove [BUG] and [FEATURE] prefixes from issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#65 Re-Add MacOS support
  classes/mcPy/McPy.py
  classes/mcPy/MultiProcessing.py
  classes/network/Connection.py
  requirements.txt
Labels: Bugfix, Dependencies

#69 Do not complain about the git install for arbitary reasons
  dependencies.py
Labels: Bugfix
